version: "3.8"
services:
  mongotest:
    image: "${TESTING_IMAGE}"
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      mongo:
          condition: service_started
      mongotest:
        condition: service_started
    # run all your tests here against the mongotest service
    command: curl --fail http://mongotest:80/animals || exit 1