version: "3"
services:
  app:
    restart: always
    image: cpustejovsky/mongotest
    ports:
      - "80:80"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - /data/db
    ports:
      - "27017:27017"
