version: "0.0.1"
services:
  app:
    restart: always
    image: mongotest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017:27017"
#    volumes:
      - /data/db
    ports:
      - "27017:27017"
